-- Table: public.usermanage

-- DROP TABLE public.usermanage;

CREATE TABLE public.usermanage
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(8) COLLATE pg_catalog."default" NOT NULL,
    role character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_usermanage" PRIMARY KEY (id)
)


TABLESPACE pg_default;

ALTER TABLE public.usermanage
    OWNER to postgres;

-- Table: public.friend

-- DROP TABLE public.friend;

CREATE TABLE public.friend
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    usermanageid bigint NOT NULL,
    CONSTRAINT "PK_friend" PRIMARY KEY (id),
    CONSTRAINT "FK_friend_usermanage_usermanageid" FOREIGN KEY (usermanageid)
        REFERENCES public.usermanage (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE public.friend
    OWNER to postgres;
-- Index: IX_friend_usermanageid

-- DROP INDEX public."IX_friend_usermanageid";

CREATE INDEX "IX_friend_usermanageid"
    ON public.friend USING btree
    (usermanageid ASC NULLS LAST)
    TABLESPACE pg_default;

-- Table: public.game

-- DROP TABLE public.game;

CREATE TABLE public.game
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    usermanageid bigint NOT NULL,
    CONSTRAINT "PK_game" PRIMARY KEY (id),
    CONSTRAINT "FK_game_usermanage_usermanageid" FOREIGN KEY (usermanageid)
        REFERENCES public.usermanage (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE public.game
    OWNER to postgres;
-- Index: IX_game_usermanageid

-- DROP INDEX public."IX_game_usermanageid";

CREATE INDEX "IX_game_usermanageid"
    ON public.game USING btree
    (usermanageid ASC NULLS LAST)
    TABLESPACE pg_default;

-- Table: public.locategame

-- DROP TABLE public.locategame;

CREATE TABLE public.locategame
(
    gameid bigint NOT NULL,
    friendid bigint NOT NULL,
    usermanageid bigint NOT NULL,
    CONSTRAINT "PK_locategame" PRIMARY KEY (gameid, friendid),
    CONSTRAINT "FK_locategame_usermanage_usermanageid" FOREIGN KEY (usermanageid)
        REFERENCES public.usermanage (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE public.locategame
    OWNER to postgres;
-- Index: IX_locategame_usermanageid

-- DROP INDEX public."IX_locategame_usermanageid";

CREATE INDEX "IX_locategame_usermanageid"
    ON public.locategame USING btree
    (usermanageid ASC NULLS LAST)
    TABLESPACE pg_default;


insert into public.usermanage(id, email, password, role) values(100, 'admin', 'admin', 'admin');
